tasks:
  - name: Installing Python utils
    before: |
      sudo apt-get update && sudo apt upgrade -y
      sudo apt-get install python3 python3-pip -y
      pip install --upgrade pip
      pip install openai
      pip install requests

